"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { Eye,EyeOff,Mail } from "lucide-react";
import { createSupabaseBrowser } from "@/lib/supabase/browser";

export function AuthForm({mode}:{mode:"login"|"register"}){const router=useRouter();const [error,setError]=useState("");const [pending,setPending]=useState(false);const [showPassword,setShowPassword]=useState(false);const [otpLogin,setOtpLogin]=useState(false);
  async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(pending)return;setPending(true);setError("");const form=new FormData(e.currentTarget);const email=String(form.get("email")||"").trim();const password=String(form.get("password")||"");const confirm=String(form.get("confirm")||"");const supabase=createSupabaseBrowser();
    if(!supabase){setError("Authentication is not configured yet. Add the Supabase URL and publishable key to .env.local.");setPending(false);return}
    if(mode==="register"&&password!==confirm){setError("Passwords do not match.");setPending(false);return}
    if(otpLogin){const {error:otpError}=await supabase.auth.signInWithOtp({email,options:{shouldCreateUser:false}});if(otpError)setError(otpError.message);else router.push(`/verify-email?email=${encodeURIComponent(email)}&flow=magiclink`);setPending(false);return}
    const result=mode==="login"?await supabase.auth.signInWithPassword({email,password}):await supabase.auth.signUp({email,password,options:{data:{display_name:String(form.get("name")||"")}}});
    if(result.error)setError(safeAuthError(result.error.message));else if(mode==="register"&&!result.data.session)router.push(`/verify-email?email=${encodeURIComponent(email)}&flow=signup`);else{router.push("/dashboard");router.refresh()}setPending(false)}
  return <form onSubmit={submit} className="mt-9 space-y-5" noValidate>{mode==="register"&&<Field label="Name"><input name="name" autoComplete="name" minLength={2} required className="auth-input" placeholder="Ada Lovelace"/></Field>}<Field label="Email address"><input name="email" type="email" autoComplete="email" required className="auth-input" placeholder="you@example.com"/></Field>{!otpLogin&&<><Field label="Password"><PasswordInput name="password" visible={showPassword} toggle={()=>setShowPassword(v=>!v)} autoComplete={mode==="login"?"current-password":"new-password"}/></Field>{mode==="register"&&<Field label="Confirm password"><PasswordInput name="confirm" visible={showPassword} toggle={()=>setShowPassword(v=>!v)} autoComplete="new-password"/></Field>}</>}
    {error&&<p role="alert" className="border-l-2 border-red-400 bg-red-400/5 px-4 py-3 text-sm text-red-300">{error}</p>}<button disabled={pending} className="auth-primary">{pending?"Please wait…":otpLogin?"Send email code":mode==="login"?"Sign in":"Create account"}</button>
    {mode==="login"&&<><div className="flex items-center justify-between gap-4 text-xs"><Link href="/forgot-password" className="text-zinc-500 hover:text-white">Forgot password?</Link><button type="button" onClick={()=>{setOtpLogin(v=>!v);setError("")}} className="inline-flex items-center gap-2 text-lime-300 hover:text-lime-200"><Mail size={13}/>{otpLogin?"Use password":"Sign in with email code"}</button></div></>}
    <p className="border-t border-white/8 pt-5 text-sm text-zinc-500">{mode==="login"?"New to DevHub? ":"Already have an account? "}<Link href={mode==="login"?"/register":"/login"} className="text-white hover:text-lime-300">{mode==="login"?"Create an account":"Sign in"}</Link></p></form>}

function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block text-xs font-medium text-zinc-400">{label}<span className="mt-2 block">{children}</span></label>}
function PasswordInput({name,visible,toggle,autoComplete}:{name:string;visible:boolean;toggle:()=>void;autoComplete:string}){return <span className="relative block"><input name={name} type={visible?"text":"password"} autoComplete={autoComplete} minLength={8} required className="auth-input pr-12" placeholder="Minimum 8 characters"/><button type="button" onClick={toggle} aria-label={visible?"Hide password":"Show password"} className="absolute right-3 top-1/2 -translate-y-1/2 p-2 text-zinc-600 hover:text-white">{visible?<EyeOff size={17}/>:<Eye size={17}/>}</button></span>}
function safeAuthError(message:string){if(/invalid login/i.test(message))return "Email or password is incorrect.";if(/email not confirmed/i.test(message))return "Verify your email before signing in.";return message}
