"use client";
import { useEffect,useRef,useState } from "react"; import Image from "next/image"; import Link from "next/link"; import { BookOpen,ChevronRight,Clock3,GitFork,LoaderCircle,Search,Star,Users } from "lucide-react"; import type { GitHubRepo,GitHubUser } from "@/types/github"; import { compactNumber,formatDate } from "@/lib/analytics";
type Mode="developers"|"repositories"; type Item=GitHubUser|GitHubRepo;
export function SearchExperience(){const [mode,setMode]=useState<Mode>("developers"),[query,setQuery]=useState(""),[items,setItems]=useState<Item[]>([]),[page,setPage]=useState(1),[total,setTotal]=useState(0),[loading,setLoading]=useState(false),[loadingMore,setLoadingMore]=useState(false),[error,setError]=useState("");const request=useRef(0);
  useEffect(()=>{if(query.trim().length<2)return;const id=++request.current;const timer=setTimeout(async()=>{setLoading(true);setError("");try{const result=await fetchPage(mode,query,1);if(id!==request.current)return;setItems(result.items);setTotal(result.total_count);setPage(1)}catch(e){if(id===request.current)setError(e instanceof Error?e.message:"Search failed")}finally{if(id===request.current)setLoading(false)}},350);return()=>clearTimeout(timer)},[query,mode]);
  function changeMode(value:Mode){request.current++;setMode(value);setItems([]);setTotal(0);setError("")}
  async function loadMore(){if(loadingMore)return;setLoadingMore(true);try{const next=page+1,result=await fetchPage(mode,query,next);setItems(current=>[...current,...result.items]);setPage(next)}catch(e){setError(e instanceof Error?e.message:"Could not load more results")}finally{setLoadingMore(false)}}
  const idle=query.trim().length<2;return <div><div className="search-command"><div className="search-switch" role="tablist">{(["developers","repositories"] as Mode[]).map(value=><button role="tab" aria-selected={mode===value} key={value} onClick={()=>changeMode(value)}>{value}</button>)}</div><label className="search-input"><Search/><span className="sr-only">Search {mode}</span><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder={mode==="developers"?"Search a GitHub developer":"Search owner, repository or technology"}/><kbd>⌘ K</kbd></label><div className="search-meta"><span>GitHub REST / live</span><span>{total?`${compactNumber(total)} results`:"Type at least 2 characters"}</span></div></div>
    <div className="mt-8" aria-live="polite">{loading&&<SearchSkeleton/>}{error&&<div className="search-state"><strong>{/rate limit/i.test(error)?"GitHub rate limit reached":"Search unavailable"}</strong><p>{error}</p></div>}{idle&&!loading&&<div className="search-empty-grid"><div><Search/><strong>One query. Connected context.</strong><p>Search developers or repositories to open a full intelligence view.</p></div><div className="search-shortcuts"><span>Try</span>{["torvalds","vercel/next.js","supabase","rust-lang/rust"].map(x=><button key={x} onClick={()=>setQuery(x)}>{x}<ChevronRight/></button>)}</div></div>}{!idle&&!loading&&!error&&items.length===0&&<div className="search-state"><strong>No matching signals</strong><p>Try a broader name or remove special characters.</p></div>}
      {!loading&&items.length>0&&<div className="search-results-list">{items.map(item=>"login" in item?<DeveloperRow key={item.id} item={item}/>:<RepositoryRow key={item.id} item={item}/>)}</div>}{items.length<total&&items.length>0&&<button onClick={loadMore} disabled={loadingMore} className="search-load-more">{loadingMore?<LoaderCircle className="animate-spin"/>:null}{loadingMore?"Loading signals…":"Load more results"}</button>}</div></div>}
async function fetchPage(mode:Mode,query:string,page:number){const base=mode==="developers"?"/api/github/users/search":"/api/github/repositories/search";const res=await fetch(`${base}?q=${encodeURIComponent(query)}&page=${page}`);const body=await res.json();if(!res.ok)throw new Error(body.error?.message||"Search failed");return body.data as {items:Item[];total_count:number}}
function DeveloperRow({item}:{item:GitHubUser}){return <Link href={`/developer/${item.login}`} className="search-row group"><Image src={item.avatar_url} alt="" width={52} height={52} className="size-12 rounded-full ring-1 ring-white/10"/><div className="min-w-0"><span className="row-type">Developer</span><h2>{item.name||item.login}</h2><p>@{item.login}</p></div><div className="row-detail"><Users/><span>Open developer intelligence</span></div><ChevronRight className="row-arrow"/></Link>}
function RepositoryRow({item}:{item:GitHubRepo}){return <Link href={`/repository/${item.full_name}`} className="search-row group"><div className="repo-mark"><BookOpen/></div><div className="min-w-0"><span className="row-type">Repository</span><h2>{item.full_name}</h2><p className="truncate">{item.description||"No description provided."}</p></div><div className="row-metrics"><span><Star/>{compactNumber(item.stargazers_count)}</span><span><GitFork/>{compactNumber(item.forks_count)}</span><span>{item.language||"—"}</span><span><Clock3/>{formatDate(item.updated_at)}</span></div><ChevronRight className="row-arrow"/></Link>}
function SearchSkeleton(){return <div className="search-results-list" aria-label="Loading search results">{Array.from({length:6}).map((_,i)=><div key={i} className="search-row animate-pulse"><div className="size-12 rounded-full bg-white/5"/><div className="w-full"><div className="h-3 w-20 bg-white/5"/><div className="mt-3 h-4 w-48 bg-white/5"/><div className="mt-2 h-3 max-w-sm bg-white/5"/></div></div>)}</div>}
